### ISSUE TITLE
Split runner name into given name / family name

### ISSUE THREAD

**Issue by pgaufillet** [pgaufillet/meos#1]
For now, meos runners have only one general name built as `givenName + " " + familyName`.
When needed, it extracts the given name as the first token of name, and the family name as the remaining of the string.

While it is acceptable during events, it raises issues when exporting results to French Orienteering Federation. The FFCO import function indeed compares given name and family name with its own database, rejecting inconsistent entries.

Unfortunately names are used in numerous places of meos and changing brutally the database schema would lead to a lot of potentially dangerous modifications.

A better solution would probably be to change only the runnerDB by adding locally `importedGivenName/importedFamilyName` and retrieving it at export time from the `extid` key.

**Comment by jmonclard** [comment]
Well, could be a workaround, but I think dealing correctly with given and family names consistently in MeOS would be far better. The name is also transmitted (in XML) to our display software and we would appreciate having separated family name and surname. Moreover this is perhaps an opportunity to fix issues with name containing single quotes (D'HARREVILLE is a good example). We ran in such a problem during 2016 Nationale Sud-Est in the Pilat. The quote spoiled the exported xml. No idea though how much work it is.

**Comment by pgaufillet** [comment]
I agree but as at first sight it means a lot of work and risks of regressions, let's do it step by step:
* Simple import using current meos name convention (already done in commit https://github.com/pgaufillet/meos/commit/17112fbe1bc000c74c57b0538708139382a1dbca)
* Simple fix at runnerDB level (in progress)
* Homogeneous name management in all meos functions (complex)

The bug you mentioned regarding quotes is interesting. Can you please open a specific issue about it?

**Comment by pgaufillet** [comment]
Finally solved by splitting the name field as `Family name, Given name`.

Modifying the db schema at one point would be nevertheless a good thing.
