### ISSUE TITLE
Online results: server configuration?

### ISSUE THREAD

**Issue by bagage** [pgaufillet/meos#32]
What's the expected configuration when using `Online results` service? I did not find any documentation about what meos expects the server to respond/which request it should support.

Having an nginx/apache/something else example configuration file would definitely help, i'm currently stuck with HTTP Status Error 405.

**Comment by jmonclard** [comment]
Hi Gautier,
    Pierre will probably answer, but in the meanwhile, here are my
      two cents.
    
    An example of a server configuration and the documentation of the
      protocol  can be found on MeOS website, in Resources section,
      under MeOS Online Protocol (MOP) entry : 
      http://www.melin.nu/meos/en/codes.php
    You can find a fully-fledged real time for MEDIUM TO large events
      results display on my GitHub :
      https://github.com/jmonclard/MopScreens
    You can e-mail me if I can help.
    
    Jerome
    
    
    Le 22/10/2017 à 17:52, Gautier
      Pelloux-Prayer a écrit :
    
    
      What's the expected configuration when using Online
          results service? I did not find any documentation about
        what meos expects the server to respond/which request it should
        support.
      Having an nginx/apache/something else example configuration
        file would definitely help, i'm currently stuck with HTTP Status
        Error 405.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pgaufillet/meos","title":"pgaufillet/meos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pgaufillet/meos"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Online results: server configuration? (#32)"}],"action":{"name":"View Issue","url":"https://github.com/pgaufillet/meos/issues/32"}}}

**Comment by bagage** [comment]
Thanks @jmonclard, I actually misread the website. I saw the `MeOS Online Protocol` resource but I didn't thought I would find server code here.Anyway it's all I needed for now :).
